FROM openjdk:11 AS BUILD
RUN apt update && apt install -y mvn
RUN git clone -b docker https://github.com/devopshydclub/vprofile-project.git
RUN cd vprofile-project && mvn install

FROM tomcat:9-jre11
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=BUILD vprofile-project/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war
CMD ["catalina.,sh","run"]

